version: "3.9"

services:
  backend:
    build: ./backend
    container_name: antrian-backend
    ports:
      - "1311:1311"
    env_file:
      - ./backend/.env
    restart: always

  frontend:
    build: ./frontend
    container_name: antrian-frontend
    ports:
      - "1113:1113"
    restart: always
